from commons.custom_pickle_loader import try_to_load_as_pickled_object_or_None
from commons.svm import SVM

"""
Here we train five SVMs (different kernels)

For CatBoost testing see the hog_catboost.ipynb
or go to: https://colab.research.google.com/drive/1eFhINcjZka73pFHMD1u5c_oeH7nN3Otk
"""

def test_svm():
  """
  This function performs testing of pre-trained SVM with 5 different kernels
  :return:
  """
  # loading pre-saved features generated by HOG
  features_test = try_to_load_as_pickled_object_or_None("hog_features_test.pkl")
  nums_test = try_to_load_as_pickled_object_or_None("../main_data/nums_test.pkl")

  # list of kernels to test
  kernels = ["linear", "chi", "inter", "rbf", "sigmoid"]

  for kr in kernels:
    path = './models/svm_halfdata_train_' + kr + '.dat' # loading pre-trained saved model

    loaded_svm = SVM()
    loaded_svm.load(path)
    res = loaded_svm.predict(features_test)

    # counting accuracy
    accuracy=0
    for i in range(len(res)):
      if int(res[i])==nums_test[i]:
        accuracy+=1
    accuracy = accuracy/len(res)

    print("Using SVM with {} kernel".format(kr))
    print("Accuracy: {0:.2f}%".format(accuracy*100))

if __name__ == '__main__':
    test_svm()